let characters = [
  {
    name: "Albedo",
    element: "geo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/9/91/Icon_Emoji_Paimon%27s_Paintings_11_Albedo_1.png/revision/latest?cb=20211222041525",
  },
  {
    name: "Alhaitham",
    element: "dendro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/f/f3/Icon_Emoji_Paimon%27s_Paintings_21_Alhaitham_1.png/revision/latest?cb=20230120043201",
  },
  {
    name: "Aloy",
    element: "cryo",
    icon: "https://images-ext-1.discordapp.net/external/HIkNrbXk9eycmJ-YchQRI9n1TP0sUx-2zXP2p-tYRQs/%3Fx-oss-process%3Dimage%252Fauto-orient%252C0%252Finterlace%252C1%252Fformat%252Cwebp%252Fquality%252Cq_80/https/upload-os-bbs.hoyolab.com/upload/2022/06/05/142052637/a3c9f17d7e8d330c4ca2879d2a13c84f_3990326550658445966.png?format=webp&quality=lossless&width=671&height=671",
  },
  {
    name: "Amber",
    element: "pyro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/a/a6/Icon_Emoji_Pizza_Hut_2.png/revision/latest?cb=20220819185729",
  },
  {
    name: "Arataki Itto",
    element: "geo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/b/b7/Icon_Emoji_Paimon%27s_Paintings_11_Arataki_Itto_2.png/revision/latest?cb=20211222041531",
  },
  {
    name: "Baizhu",
    element: "dendro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/6/64/Icon_Emoji_Paimon%27s_Paintings_23_Baizhu_4.png/revision/latest?cb=20230506194258",
  },
  {
    name: "Barbara",
    element: "hydro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/d/d9/Icon_Emoji_Paimon%27s_Paintings_07_Barbara_3.png/revision/latest?cb=20211231163716",
  },
  {
    name: "Beidou",
    element: "electro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/e/e4/Icon_Emoji_Paimon%27s_Paintings_08_Beidou_1.png/revision/latest?cb=20220311061829",
  },
  {
    name: "Bennett",
    element: "pyro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/6/6f/Icon_Emoji_Paimon%27s_Paintings_20_Bennett_1.png/revision/latest?cb=20221216070029",
  },
  {
    name: "Candace",
    element: "hydro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/c/c4/Icon_Emoji_Paimon%27s_Paintings_18_Candace_3.png/revision/latest?cb=20221020052644",
  },
  {
    name: "Charlotte",
    element: "cryo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/a/af/Icon_Emoji_Paimon%27s_Paintings_24_Charlotte_1.png/revision/latest?cb=20230528042736",
  },
  {
    name: "Chevreuse",
    element: "pyro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/d/d9/Icon_Emoji_Paimon%27s_Paintings_29_Chevreuse_4.png/revision/latest?cb=20231228162157",
  },
  {
    name: "Chongyun",
    element: "cryo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/5/5b/Icon_Emoji_Paimon%27s_Paintings_27_Chongyun_1.png/revision/latest?cb=20231019084154",
  },
  {
    name: "Collei",
    element: "dendro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/5/56/Icon_Emoji_Paimon%27s_Paintings_22_Collei_2.png/revision/latest?cb=20230310044014",
  },
  {
    name: "Cyno",
    element: "electro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/0/05/Icon_Emoji_Paimon%27s_Paintings_18_Cyno_3.png/revision/latest?cb=20221020052700",
  },
  {
    name: "Dehya",
    element: "pyro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/3/36/Icon_Emoji_Paimon%27s_Paintings_22_Dehya_3.png/revision/latest?cb=20230310043824",
  },
  {
    name: "Diluc",
    element: "pyro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/d/d6/Icon_Emoji_Paimon%27s_Paintings_13_Diluc_1.png/revision/latest?cb=20220610185943",
  },
  {
    name: "Diona",
    element: "cryo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/7/78/Icon_Emoji_Paimon%27s_Paintings_03_Diona_3.png/revision/latest?cb=20210906043959",
  },
  {
    name: "Dori",
    element: "electro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/0/01/Icon_Emoji_Paimon%27s_Paintings_17_Dori_2.png/revision/latest?cb=20220921015830",
  },
  {
    name: "Eula",
    element: "cryo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/d/d7/Icon_Emoji_Paimon%27s_Paintings_06_Eula_1.png/revision/latest?cb=20210906044135",
  },
  {
    name: "Faruzan",
    element: "anemo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/f/fe/Icon_Emoji_Paimon%27s_Paintings_20_Faruzan_3.png/revision/latest?cb=20221216070021",
  },
  {
    name: "Fischl",
    element: "electro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/b/b8/Icon_Emoji_Paimon%27s_Paintings_04_Fischl_2.png/revision/latest?cb=20210906044055",
  },
  {
    name: "Freminet",
    element: "cryo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/e/ea/Icon_Emoji_Paimon%27s_Paintings_26_Freminet_4.png/revision/latest?cb=20230824043506",
  },
  {
    name: "Furina",
    element: "hydro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/0/06/Icon_Emoji_Paimon%27s_Paintings_28_Furina_3.png/revision/latest?cb=20231118042303",
  },
  {
    name: "Ganyu",
    element: "cryo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/5/50/Icon_Emoji_Paimon%27s_Paintings_04_Ganyu_4.png/revision/latest?cb=20210906044036",
  },
  {
    name: "Gorou",
    element: "geo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/4/4f/Icon_Emoji_Paimon%27s_Paintings_11_Gorou_3.png/revision/latest?cb=20211222041518",
  },
  {
    name: "Hu Tao",
    element: "pyro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/9/93/Icon_Emoji_Paimon%27s_Paintings_05_Hu_Tao_1.png/revision/latest?cb=20210906044057",
  },
  {
    name: "Jean",
    element: "anemo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/b/b3/Icon_Emoji_Paimon%27s_Paintings_13_Jean_1.png/revision/latest?cb=20220610190014",
  },
  {
    name: "Kaedehara Kazuha",
    element: "anemo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/b/b5/Icon_Emoji_Paimon%27s_Paintings_07_Kaedehara_Kazuha_1.png/revision/latest?cb=20220101201357",
  },
  {
    name: "Kaeya",
    element: "cryo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/9/95/Icon_Emoji_Paimon%27s_Paintings_13_Kaeya_1.png/revision/latest?cb=20220311051746",
  },
  {
    name: "Kamisato Ayaka",
    element: "cryo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/0/00/Icon_Emoji_Paimon%27s_Paintings_08_Kamisato_Ayaka_1.png/revision/latest?cb=20220311062030",
  },
  {
    name: "Kamisato Ayato",
    element: "hydro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/a/a8/Icon_Emoji_Paimon%27s_Paintings_14_Kamisato_Ayato_2.png/revision/latest?cb=20220422090615",
  },
  {
    name: "Kaveh",
    element: "dendro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/1/11/Icon_Emoji_Paimon%27s_Paintings_23_Kaveh_3.png/revision/latest?cb=20230506193617",
  },
  {
    name: "Keqing",
    element: "electro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/9/9e/Icon_Emoji_Paimon%27s_Paintings_09_Keqing_2.png/revision/latest?cb=20211118222054",
  },
  {
    name: "Kirara",
    element: "dendro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/b/be/Icon_Emoji_Paimon%27s_Paintings_24_Kirara_1.png/revision/latest?cb=20230528042229",
  },
  {
    name: "Klee",
    element: "pyro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/4/48/Icon_Emoji_Paimon%27s_Paintings_07_Klee_3.png/revision/latest?cb=20211231163452",
  },
  {
    name: "Kujou Sara",
    element: "electro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/2/23/Icon_Emoji_Paimon%27s_Paintings_09_Kujou_Sara_4.png/revision/latest?cb=20211118213901",
  },
  {
    name: "Kuki Shinobu",
    element: "electro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/b/bb/Icon_Emoji_Paimon%27s_Paintings_15_Kuki_Shinobu_3.png/revision/latest?cb=20220624044015",
  },
  {
    name: "Layla",
    element: "cryo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/b/bb/Icon_Emoji_Paimon%27s_Paintings_19_Layla_2.png/revision/latest?cb=20221124043130",
  },
  {
    name: "Lisa",
    element: "electro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/9/9a/Icon_Emoji_Paimon%27s_Paintings_13_Lisa_1.png/revision/latest?cb=20220311051626",
  },
  {
    name: "Lynette",
    element: "anemo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/1/1d/Icon_Emoji_Paimon%27s_Paintings_26_Lynette_1.png/revision/latest?cb=20230824043538",
  },
  {
    name: "Lyney",
    element: "pyro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/3/3c/Icon_Emoji_Paimon%27s_Paintings_28_Lyney_1.png/revision/latest?cb=20231118042325",
  },
  {
    name: "Mika",
    element: "cryo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/6/6b/Icon_Emoji_Paimon%27s_Paintings_22_Mika_3.png/revision/latest?cb=20230310044228",
  },
  {
    name: "Mona",
    element: "hydro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/4/44/Icon_Emoji_Paimon%27s_Paintings_02_Mona_1.png/revision/latest?cb=20210906043913",
  },
  {
    name: "Nahida",
    element: "dendro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/5/58/Icon_Emoji_Paimon%27s_Paintings_19_Nahida_4.png/revision/latest?cb=20221124043007",
  },
  {
    name: "Navia",
    element: "geo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/2/2c/Icon_Emoji_Paimon%27s_Paintings_29_Navia_2.png/revision/latest?cb=20231228162411",
  },
  {
    name: "Neuvillette",
    element: "hydro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/9/9e/Icon_Emoji_Paimon%27s_Paintings_26_Neuvillette_1.png/revision/latest?cb=20230824043610",
  },
  {
    name: "Nilou",
    element: "hydro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/5/57/Icon_Emoji_Paimon%27s_Paintings_18_Nilou_3.png/revision/latest?cb=20221020052716",
  },
  {
    name: "Ningguang",
    element: "geo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/f/ff/Icon_Emoji_Paimon%27s_Paintings_12_Ningguang_2.png/revision/latest?cb=20220128151006",
  },
  {
    name: "Noelle",
    element: "geo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/d/d6/Icon_Emoji_KFC_11.png/revision/latest?cb=20230924191703",
  },
  {
    name: "Qiqi",
    element: "cryo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/6/68/Icon_Emoji_Paimon%27s_Paintings_02_Qiqi_3.png/revision/latest?cb=20210906043925",
  },
  {
    name: "Raiden Shogun",
    element: "electro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/e/e5/Icon_Emoji_Paimon%27s_Paintings_13_Raiden_Shogun_1.png/revision/latest?cb=20220311050338",
  },
  {
    name: "Razor",
    element: "electro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/8/89/Icon_Emoji_Paimon%27s_Paintings_18_Razor_4.png/revision/latest?cb=20221020052736",
  },
  {
    name: "Rosaria",
    element: "cryo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/1/19/Icon_Emoji_Paimon%27s_Paintings_06_Rosaria_1.png/revision/latest?cb=20210906044204",
  },
  {
    name: "Sangonomiya Kokomi",
    element: "hydro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/2/27/Icon_Emoji_Paimon%27s_Paintings_13_Sangonomiya_Kokomi_2.png/revision/latest?cb=20220311051423",
  },
  {
    name: "Sayu",
    element: "anemo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/1/18/Icon_Emoji_Paimon%27s_Paintings_08_Sayu_2.png/revision/latest?cb=20220311053737",
  },
  {
    name: "Shenhe",
    element: "cryo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/d/db/Icon_Emoji_Paimon%27s_Paintings_12_Shenhe_3.png/revision/latest?cb=20220128144752",
  },
  {
    name: "Shikanoin Heizou",
    element: "anemo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/0/04/Icon_Emoji_Paimon%27s_Paintings_16_Shikanoin_Heizou_1.png/revision/latest?cb=20220812043842",
  },
  {
    name: "Sucrose",
    element: "anemo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/9/94/Icon_Emoji_Paimon%27s_Paintings_02_Sucrose_1.png/revision/latest/scale-to-width-down/1000?cb=20220311054641",
  },
  {
    name: "Tartaglia",
    element: "hydro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/9/9a/Icon_Emoji_Paimon%27s_Paintings_26_Tartaglia_1.png/revision/latest?cb=20230824043619",
  },
  {
    name: "Thoma",
    element: "pyro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/6/66/Icon_Emoji_Paimon%27s_Paintings_10_Thoma_3.png/revision/latest?cb=20211118233542",
  },
  {
    name: "Tighnari",
    element: "dendro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/2/22/Icon_Emoji_Paimon%27s_Paintings_23_Tighnari_1.png/revision/latest?cb=20230506193938",
  },
  {
    name: "Traveler (Anemo)",
    element: "anemo",
    icon: "https://s3.getstickerpack.com/storage/uploads/sticker-pack/genshin-impact-aether/sticker_23.png?0f2c13fdc72114f0dd57ecf3598d667f",
  },
  {
    name: "Traveler (Geo)",
    element: "anemo",
    icon: "https://s3.getstickerpack.com/storage/uploads/sticker-pack/genshin-impact-aether/sticker_23.png?0f2c13fdc72114f0dd57ecf3598d667f",
  },
  {
    name: "Traveler (Electro)",
    element: "anemo",
    icon: "https://s3.getstickerpack.com/storage/uploads/sticker-pack/genshin-impact-aether/sticker_23.png?0f2c13fdc72114f0dd57ecf3598d667f",
  },
  {
    name: "Traveler (Dendro)",
    element: "anemo",
    icon: "https://s3.getstickerpack.com/storage/uploads/sticker-pack/genshin-impact-aether/sticker_23.png?0f2c13fdc72114f0dd57ecf3598d667f",
  },
  {
    name: "Traveler (Hydro)",
    element: "anemo",
    icon: "https://s3.getstickerpack.com/storage/uploads/sticker-pack/genshin-impact-aether/sticker_23.png?0f2c13fdc72114f0dd57ecf3598d667f",
  },
  {
    name: "Venti",
    element: "anemo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/b/b9/Icon_Emoji_Paimon%27s_Paintings_02_Venti_4.png/revision/latest?cb=20210906043935",
  },
  {
    name: "Wanderer",
    element: "anemo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/4/4f/Icon_Emoji_Paimon%27s_Paintings_25_Wanderer_2.png/revision/latest?cb=20230717042342",
  },
  {
    name: "Wriothesley",
    element: "cryo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/d/d2/Icon_Emoji_Paimon%27s_Paintings_27_Wriothesley_2.png/revision/latest?cb=20231030092655",
  },
  {
    name: "Xiangling",
    element: "pyro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/d/d0/Icon_Emoji_Paimon%27s_Paintings_09_Xiangling_1.png/revision/latest?cb=20211118222339",
  },
  {
    name: "Xiao",
    element: "anemo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/7/76/Icon_Emoji_Paimon%27s_Paintings_05_Xiao_7.png/revision/latest?cb=20210906044131",
  },
  {
    name: "Xingqiu",
    element: "hydro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/b/b0/Icon_Emoji_Paimon%27s_Paintings_14_Xingqiu_1.png/revision/latest?cb=20220422091127",
  },
  {
    name: "Xinyan",
    element: "pyro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/3/3b/Icon_Emoji_Paimon%27s_Paintings_10_Xinyan_1.png/revision/latest?cb=20211118233655",
  },
  {
    name: "Yae Miko",
    element: "electro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/d/d2/Icon_Emoji_Paimon%27s_Paintings_24_Yae_Miko_1.png/revision/latest?cb=20230528042619",
  },
  {
    name: "Yanfei",
    element: "pyro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/7/7a/Icon_Emoji_Paimon%27s_Paintings_06_Yanfei_4.png/revision/latest?cb=20210906044152",
  },
  {
    name: "Yaoyao",
    element: "anemo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/0/01/Icon_Emoji_Paimon%27s_Paintings_21_Yaoyao_2.png/revision/latest?cb=20230120042618",
  },
  {
    name: "Yelan",
    element: "hydro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/2/2a/Icon_Emoji_Paimon%27s_Paintings_15_Yelan_4.png/revision/latest?cb=20220624044002",
  },
  {
    name: "Yoimiya",
    element: "pyro",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/1/11/Icon_Emoji_Paimon%27s_Paintings_16_Yoimiya_1.png/revision/latest?cb=20220812043355",
  },
  {
    name: "Yun Jin",
    element: "geo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/0/05/Icon_Emoji_Paimon%27s_Paintings_12_Yun_Jin_2.png/revision/latest?cb=20220128145149",
  },
  {
    name: "Zhongli",
    element: "geo",
    icon: "https://static.wikia.nocookie.net/gensin-impact/images/4/48/Icon_Emoji_Paimon%27s_Paintings_12_Zhongli_1.png/revision/latest?cb=20220128150721",
  },
  {
    name: "Xianyun",
    element: "anemo",
    icon: "https://cdn.discordapp.com/emojis/1200009842354573416.webp?size=96&quality=lossless",
  },
  {
    name: "Gaming",
    element: "pyro",
    icon: "https://cdn.discordapp.com/attachments/827839674202587146/1201414391111884911/Bow.png?ex=65c9bb58&is=65b74658&hm=ee42c7c2b4e0b4f2523b469aecea6a8cad32415137415f7ba943e4917c8401b9&",
  },
];

let teams = [
  ["Albedo", "Arataki Itto", "Gorou", "Kuki Shinobu"],
  ["Albedo", "Noelle", "Gorou", "Yun Jin"],
  ["Albedo", "Zhongli", "Hu Tao", "Xingqiu"],
  ["Albedo", "Zhongli", "Xiao", "Faruzan"],
  ["Alhaitham", "Beidou", "Kuki Shinobu", "Nahida"],
  ["Alhaitham", "Yelan", "Kuki Shinobu", "Nahida"],
  ["Alhaitham", "Xingqiu", "Thoma", "Fischl"],
  ["Aloy", "Bennett", "Kaedehara Kazuha", "Xiangling"],
  ["Aloy", "Bennett", "Xiangling", "Shenhe"],
  ["Aloy", "Kamisato Ayaka", "Kaedehara Kazuha", "Sangonomiya Kokomi"],
  ["Aloy", "Ganyu", "Venti", "Mona"],
  ["Amber", "Rosaria", "Layla", "Bennett"],
  ["Amber", "Collei", "Sangonomiya Kokomi", "Rosaria"],
  ["Arataki Itto", "Gorou", "Albedo", "Zhongli"],
  ["Arataki Itto", "Albedo", "Gorou", "Layla"],
  ["Arataki Itto", "Albedo", "Gorou", "Bennett"],
  ["Arataki Itto", "Albedo", "Gorou", "Fischl"],
  ["Baizhu", "Keqing", "Fischl", "Kaedehara Kazuha"],
  ["Baizhu", "Cyno", "Beidou", "Nahida"],
  ["Baizhu", "Nilou", "Sangonomiya Kokomi", "Nahida"],
  ["Barbara", "Xiangling", "Bennett", "Sucrose"],
  ["Barbara", "Jean", "Bennett", "Kaedehara Kazuha"],
  ["Beidou", "Sucrose", "Fischl", "Xingqiu"],
  ["Bennett", "Ganyu", "Xiangling", "Zhongli"],
  ["Bennett", "Chongyun", "Kaedehara Kazuha", "Diona"],
  ["Candace", "Yaoyao", "Nilou", "Traveler (Dendro)"],
  ["Candace", "Beidou", "Kuki Shinobu", "Traveler (Dendro)"],
  ["Candace", "Beidou", "Raiden Shogun", "Nahida"],
  ["Candace", "Collei", "Bennett", "Kaedehara Kazuha"],
  ["Charlotte", "Furina", "Kaedehara Kazuha", "Neuvillette"],
  ["Charlotte", "Furina", "Hu Tao", "Rosaria"],
  ["Charlotte", "Furina", "Kaedehara Kazuha", "Yelan"],
  ["Charlotte", "Kamisato Ayaka", "Venti", "Furina"],
  ["Chevreuse", "Xiangling", "Raiden Shogun", "Bennett"],
  ["Chevreuse", "Fischl", "Yoimiya", "Bennett"],
  ["Chevreuse", "Fischl", "Yae Miko", "Bennett"],
  ["Chevreuse", "Fischl", "Beidou", "Yanfei"],
  ["Chongyun", "Shenhe", "Xianyun", "Xiangling"],
  ["Collei"],
  ["Cyno", "Nahida", "Yelan", "Kuki Shinobu"],
  ["Cyno", "Nahida", "Xingqiu", "Baizhu"],
  ["Cyno", "Nahida", "Fischl", "Baizhu"],
  ["Cyno", "Yaoyao", "Fischl", "Kaedehara Kazuha"],
  ["Cyno", "Nahida", "Yae Miko", "Zhongli"],
  ["Cyno", "Traveler (Dendro)", "Xingqiu", "Beidou"],
  ["Dehya", "Bennett", "Xiangling", "Kaedehara Kazuha"],
  ["Dehya", "Bennett", "Xiangling", "Ganyu"],
  ["Dehya", "Bennett", "Nahida", "Ganyu"],
  ["Dehya", "Bennett", "Lyney", "Kaedehara Kazuha"],
  ["Dehya", "Bennett", "Mona", "Kaedehara Kazuha"],
  ["Dehya", "Bennett", "Faruzan", "Wanderer"],
  ["Dehya", "Xingqiu", "Nahida", "Kuki Shinobu"],
  ["Dehya", "Hu Tao", "Yelan", "Kaedehara Kazuha"],
  ["Dehya", "Yoimiya", "Yelan", "Xingqiu"],
  ["Diluc", "Rosaria", "Bennett", "Sucrose"],
  ["Diluc", "Kaeya", "Bennett", "Sucrose"],
  ["Diluc", "Kaeya", "Bennett", "Kaedehara Kazuha"],
  ["Diluc", "Xingqiu", "Bennett", "Sucrose"],
  ["Diluc", "Xingqiu", "Bennett", "Yelan"],
  ["Diluc", "Xingqiu", "Bennett", "Fischl"],
  ["Diluc", "Xingqiu", "Sucrose", "Fischl"],
  ["Diluc", "Xingqiu", "Beidou", "Fischl"],
  ["Diluc", "Xingqiu", "Albedo", "Zhongli"],
  ["Diluc", "Furina", "Bennett", "Xianyun"],
  ["Diona"],
  ["Dori", "Jean", "Nahida", "Tartaglia"],
  ["Dori", "Jean", "Nahida", "Yelan"],
  ["Dori", "Jean", "Traveler (Dendro)", "Xingqiu"],
  ["Dori", "Eula", "Shenhe", "Rosaria"],
  ["Eula", "Fischl", "Diona", "Rosaria"],
  ["Eula", "Kuki Shinobu", "Shenhe", "Rosaria"],
  ["Eula", "Raiden Shogun", "Diona", "Rosaria"],
  ["Eula", "Raiden Shogun", "Diona", "Lisa"],
  ["Eula", "Raiden Shogun", "Diona", "Yelan"],
  ["Eula", "Raiden Shogun", "Zhongli", "Rosaria"],
  ["Eula", "Fischl", "Beidou", "Diona"],
  ["Faruzan"],
  ["Fischl"],
  ["Freminet", "Xingqiu", "Fischl", "Layla"],
  ["Freminet", "Xingqiu", "Lynette", "Layla"],
  ["Freminet", "Yelan", "Jean", "Shenhe"],
  ["Freminet", "Xingqiu", "Fischl", "Beidou"],
  ["Freminet", "Yelan", "Kuki Shinobu", "Shenhe"],
  ["Freminet", "Sangonomiya Kokomi", "Yae Miko", "Rosaria"],
  ["Freminet", "Sangonomiya Kokomi", "Kaedehara Kazuha", "Rosaria"],
  ["Freminet", "Chongyun", "Kaedehara Kazuha", "Xingqiu"],
  ["Furina", "Zhongli", "Neuvillette", "Kaedehara Kazuha"],
  ["Furina", "Kaedehara Kazuha", "Sangonomiya Kokomi", "Xingqiu"],
  ["Furina", "Mika", "Yelan", "Wriothesley"],
  ["Furina", "Noelle", "Gorou", "Albedo"],
  ["Furina", "Bennett", "Xiangling", "Xingqiu"],
  ["Furina", "Baizhu", "Cyno", "Nahida"],
  ["Furina", "Baizhu", "Raiden Shogun", "Alhaitham"],
  ["Furina", "Yaoyao", "Collei", "Nilou"],
  ["Furina", "Mika", "Eula", "Raiden Shogun"],
  ["Furina", "Mika", "Faruzan", "Wanderer"],
  ["Furina", "Jean", "Hu Tao", "Xingqiu"],
  ["Ganyu", "Venti", "Mona", "Layla"],
  ["Ganyu", "Venti", "Mona", "Rosaria"],
  ["Ganyu", "Venti", "Mona", "Shenhe"],
  ["Ganyu", "Kaedehara Kazuha", "Mona", "Layla"],
  ["Ganyu", "Kaedehara Kazuha", "Mona", "Diona"],
  ["Ganyu", "Venti", "Sangonomiya Kokomi", "Shenhe"],
  ["Ganyu", "Venti", "Sangonomiya Kokomi", "Rosaria"],
  ["Ganyu", "Venti", "Nilou", "Rosaria"],
  ["Ganyu", "Kaedehara Kazuha", "Sangonomiya Kokomi", "Kamisato Ayaka"],
  ["Ganyu", "Bennett", "Xiangling", "Zhongli"],
  ["Ganyu", "Bennett", "Nahida", "Zhongli"],
  ["Ganyu", "Bennett", "Nahida", "Xinyan"],
  ["Ganyu", "Bennett", "Nahida", "Kaedehara Kazuha"],
  ["Gorou"],
  ["Hu Tao"],
  ["Kaedehara Kazuha"],
  ["Kaeya"],
  ["Kamisato Ayaka"],
  ["Kamisato Ayato", "Bennett", "Fischl", "Kaedehara Kazuha"],
  ["Kamisato Ayato", "Yae Miko", "Fischl", "Jean"],
  ["Kamisato Ayato", "Beidou", "Fischl", "Jean"],
  ["Kamisato Ayato", "Beidou", "Fischl", "Bennett"],
  ["Kamisato Ayato", "Bennett", "Xiangling", "Fischl"],
  ["Kamisato Ayato", "Bennett", "Xiangling", "Kaedehara Kazuha"],
  ["Kamisato Ayato", "Bennett", "Xiangling", "Sucrose"],
  ["Kamisato Ayato", "Ganyu", "Diona", "Venti"],
  ["Kamisato Ayato", "Rosaria", "Kaeya", "Kaedehara Kazuha"],
  ["Kaveh", "Nilou", "Baizhu", "Xingqiu"],
  ["Kaveh", "Xingqiu", "Sangonomiya Kokomi", "Kaedehara Kazuha"],
  ["Kaveh", "Nahida", "Sangonomiya Kokomi", "Yelan"],
  ["Kaveh", "Thoma", "Fischl", "Xingqiu"],
  ["Kaveh", "Yelan", "Kaedehara Kazuha", "Bennett"],
  ["Kaveh", "Raiden Shogun", "Traveler (Dendro)", "Xingqiu"],
  ["Kaveh", "Kuki Shinobu", "Yelan", "Xingqiu"],
  ["Keqing"],
  ["Kirara"],
  ["Klee", "Kaedehara Kazuha", "Bennett", "Xiangling"],
  ["Klee", "Kaedehara Kazuha", "Bennett", "Venti"],
  ["Klee", "Bennett", "Xingqiu", "Yelan"],
  ["Klee", "Bennett", "Mona", "Venti"],
  ["Klee", "Xingqiu", "Bennett", "Xiangling"],
  ["Klee", "Xingqiu", "Nahida", "Kirara"],
  ["Klee", "Xingqiu", "Nahida", "Baizhu"],
  ["Klee", "Kaedehara Kazuha", "Bennett", "Rosaria"],
  ["Klee", "Beidou", "Bennett", "Fischl"],
  ["Kujou Sara"],
  ["Kuki Shinobu"],
  ["Layla"],
  ["Lisa"],
  ["Lynette"],
  ["Lyney"],
  ["Mika"],
  ["Mona"],
  ["Nahida"],
  ["Navia", "Zhongli", "Fischl", "Bennett"],
  ["Navia", "Ningguang", "Furina", "Sangonomiya Kokomi"],
  ["Navia", "Zhongli", "Furina", "Bennett"],
  ["Neuvillette"],
  ["Nilou"],
  ["Ningguang", "Zhongli", "Yae Miko", "Fischl"],
  ["Ningguang", "Zhongli", "Albedo", "Fischl"],
  ["Ningguang", "Zhongli", "Bennett", "Fischl"],
  ["Ningguang", "Zhongli", "Bennett", "Gorou"],
  ["Ningguang", "Zhongli", "Albedo", "Kujou Sara"],
  ["Ningguang", "Xiangling", "Albedo", "Bennett"],
  ["Noelle"],
  ["Qiqi"],
  ["Raiden Shogun", "Xiangling", "Xingqiu", "Bennett"],
  ["Raiden Shogun", "Sucrose", "Fischl", "Bennett"],
  ["Raiden Shogun", "Lisa", "Venti", "Sangonomiya Kokomi"],
  ["Raiden Shogun", "Nahida", "Traveler (Dendro)", "Sangonomiya Kokomi"],
  ["Raiden Shogun", "Kujou Sara", "Kaedehara Kazuha", "Bennett"],
  ["Raiden Shogun", "Yae Miko", "Kaedehara Kazuha", "Jean"],
  ["Razor", "Albedo", "Zhongli", "Rosaria"],
  ["Razor", "Albedo", "Zhongli", "Xingqiu"],
  ["Razor", "Fischl", "Zhongli", "Rosaria"],
  ["Razor", "Fischl", "Xingqiu", "Diona"],
  ["Razor", "Bennett", "Xingqiu", "Nahida"],
  ["Razor", "Baizhu", "Furina", "Nahida"],
  ["Razor", "Baizhu", "Xingqiu", "Nahida"],
  ["Razor", "Baizhu", "Yelan", "Nahida"],
  ["Razor", "Xingqiu", "Yelan", "Qiqi"],
  ["Rosaria"],
  ["Sangonomiya Kokomi"],
  ["Sayu", "Keqing", "Traveler (Dendro)", "Fischl"],
  ["Sayu", "Xiao", "Zhongli", "Fischl"],
  ["Sayu", "Bennett", "Xiangling", "Kaedehara Kazuha"],
  ["Sayu", "Sangonomiya Kokomi", "Rosaria", "Bennett"],
  ["Sayu", "Kaeya", "Xiangling", "Bennett"],
  ["Sayu", "Sangonomiya Kokomi", "Fischl", "Sucrose"],
  ["Sayu", "Sangonomiya Kokomi", "Nahida", "Kuki Shinobu"],
  ["Sayu", "Nahida", "Fischl", "Lisa"],
  ["Sayu", "Nahida", "Fischl", "Beidou"],
  ["Shenhe"],
  ["Shikanoin Heizou", "Hu Tao", "Thoma", "Xingqiu"],
  ["Shikanoin Heizou", "Bennett", "Xiangling", "Tartaglia"],
  ["Shikanoin Heizou", "Bennett", "Xiangling", "Xingqiu"],
  ["Shikanoin Heizou", "Bennett", "Xiangling", "Rosaria"],
  ["Shikanoin Heizou", "Bennett", "Xiangling", "Kaedehara Kazuha"],
  ["Shikanoin Heizou", "Bennett", "Xiangling", "Faruzan"],
  ["Sucrose"],
  ["Tartaglia", "Bennett", "Xiangling", "Sucrose"],
  ["Tartaglia", "Bennett", "Xiangling", "Venti"],
  ["Tartaglia", "Bennett", "Xiangling", "Jean"],
  ["Tartaglia", "Bennett", "Xiangling", "Albedo"],
  ["Tartaglia", "Bennett", "Xiangling", "Zhongli"],
  ["Tartaglia", "Bennett", "Xiangling", "Xingqiu"],
  ["Tartaglia", "Bennett", "Xiangling", "Traveler (Anemo)"],
  ["Tartaglia", "Bennett", "Xiangling", "Kaedehara Kazuha"],
  ["Tartaglia", "Bennett", "Beidou", "Kujou Sara"],
  ["Tartaglia", "Bennett", "Beidou", "Fischl"],
  ["Tartaglia", "Bennett", "Beidou", "Yae Miko"],
  ["Tartaglia", "Bennett", "Xiangling", "Fischl"],
  ["Thoma"],
  ["Tighnari", "Fischl", "Kuki Shinobu", "Kaedehara Kazuha"],
  ["Tighnari", "Fischl", "Yae Miko", "Zhongli"],
  ["Tighnari", "Fischl", "Nahida", "Zhongli"],
  ["Tighnari", "Fischl", "Collei", "Bennett"],
  ["Tighnari", "Fischl", "Albedo", "Zhongli"],
  ["Traveler (Dendro)", "Fischl", "Xingqiu", "Sucrose"],
  ["Traveler (Electro)", "Noelle", "Gorou", "Fischl"],
  ["Traveler (Geo)", "Noelle", "Gorou", "Fischl"],
  ["Venti"],
  ["Wanderer"],
  ["Wriothesley", "Nahida", "Bennett", "Thoma"],
  ["Wriothesley", "Xiangling", "Bennett", "Furina"],
  ["Xiangling"],
  ["Xiao", "Faruzan", "Furina", "Xianyun"],
  ["Xingqiu"],
  ["Yae Miko"],
  ["Yanfei"],
  ["Yaoyao"],
  ["Yelan"],
  ["Yoimiya"],
  ["Yun Jin"],
  ["Zhongli"],
  ["Xianyun"],
  ["Gaming", "Xianyun", "Furina", "Bennett"],
];

let links = teams.reduce((acc, val) => {
  for (let i = 0; i < val.length; i++) {
    for (let j = i + 1; j < val.length; j++) {
      acc.push({
        source: val[i],
        target: val[j],
      });
    }
  }
  return acc;
}, []);

var graph = {
  nodes: [...characters],
  links: [...links],
};
