let characters = [
  {
    name: "Albedo",
    element: "geo",
    icon: "images/Albedo.webp",
  },
  {
    name: "Alhaitham",
    element: "dendro",
    icon: "images/Alhaitham.webp",
  },
  {
    name: "Aloy",
    element: "cryo",
    icon: "images/Aloy.webp",
  },
  {
    name: "Amber",
    element: "pyro",
    icon: "images/Amber.webp",
  },
  {
    name: "Arataki Itto",
    element: "geo",
    icon: "images/Arataki Itto.png",
  },
  {
    name: "Baizhu",
    element: "dendro",
    icon: "images/Baizhu.png",
  },
  {
    name: "Barbara",
    element: "hydro",
    icon: "images/Barbara.png",
  },
  {
    name: "Beidou",
    element: "electro",
    icon: "images/Beidou.png",
  },
  {
    name: "Bennett",
    element: "pyro",
    icon: "images/Bennett.png",
  },
  {
    name: "Candace",
    element: "hydro",
    icon: "images/Candace.png",
  },
  {
    name: "Charlotte",
    element: "cryo",
    icon: "images/Charlotte.png",
  },
  {
    name: "Chevreuse",
    element: "pyro",
    icon: "images/Chevreuse.png",
  },
  {
    name: "Chongyun",
    element: "cryo",
    icon: "images/Chongyun.png",
  },
  {
    name: "Collei",
    element: "dendro",
    icon: "images/Collei.png",
  },
  {
    name: "Cyno",
    element: "electro",
    icon: "images/Cyno.png",
  },
  {
    name: "Dehya",
    element: "pyro",
    icon: "images/Dehya.png",
  },
  {
    name: "Diluc",
    element: "pyro",
    icon: "images/Diluc.png",
  },
  {
    name: "Diona",
    element: "cryo",
    icon: "images/Diona.png",
  },
  {
    name: "Dori",
    element: "electro",
    icon: "images/Dori.png",
  },
  {
    name: "Eula",
    element: "cryo",
    icon: "images/Eula.png",
  },
  {
    name: "Faruzan",
    element: "anemo",
    icon: "images/Faruzan.png",
  },
  {
    name: "Fischl",
    element: "electro",
    icon: "images/Fischl.png",
  },
  {
    name: "Freminet",
    element: "cryo",
    icon: "images/Freminet.png",
  },
  {
    name: "Furina",
    element: "hydro",
    icon: "images/Furina.png",
  },
  {
    name: "Ganyu",
    element: "cryo",
    icon: "images/Ganyu.png",
  },
  {
    name: "Gorou",
    element: "geo",
    icon: "images/Gorou.png",
  },
  {
    name: "Hu Tao",
    element: "pyro",
    icon: "images/Hu Tao.png",
  },
  {
    name: "Jean",
    element: "anemo",
    icon: "images/Jean.png",
  },
  {
    name: "Kaedehara Kazuha",
    element: "anemo",
    icon: "images/Kaedehara Kazuha.png",
  },
  {
    name: "Kaeya",
    element: "cryo",
    icon: "images/Kaeya.png",
  },
  {
    name: "Kamisato Ayaka",
    element: "cryo",
    icon: "images/Kamisato Ayaka.png",
  },
  {
    name: "Kamisato Ayato",
    element: "hydro",
    icon: "images/Kamisato Ayato.png",
  },
  {
    name: "Kaveh",
    element: "dendro",
    icon: "images/Kaveh.png",
  },
  {
    name: "Keqing",
    element: "electro",
    icon: "images/Keqing.png",
  },
  {
    name: "Kirara",
    element: "dendro",
    icon: "images/Kirara.png",
  },
  {
    name: "Klee",
    element: "pyro",
    icon: "images/Klee.png",
  },
  {
    name: "Kujou Sara",
    element: "electro",
    icon: "images/Kujou Sara.png",
  },
  {
    name: "Kuki Shinobu",
    element: "electro",
    icon: "images/Kuki Shinobu.png",
  },
  {
    name: "Layla",
    element: "cryo",
    icon: "images/Layla.png",
  },
  {
    name: "Lisa",
    element: "electro",
    icon: "images/Lisa.png",
  },
  {
    name: "Lynette",
    element: "anemo",
    icon: "images/Lynette.png",
  },
  {
    name: "Lyney",
    element: "pyro",
    icon: "images/Lyney.png",
  },
  {
    name: "Mika",
    element: "cryo",
    icon: "images/Mika.png",
  },
  {
    name: "Mona",
    element: "hydro",
    icon: "images/Mona.png",
  },
  {
    name: "Nahida",
    element: "dendro",
    icon: "images/Nahida.png",
  },
  {
    name: "Navia",
    element: "geo",
    icon: "images/Navia.png",
  },
  {
    name: "Neuvillette",
    element: "hydro",
    icon: "images/Neuvillette.png",
  },
  {
    name: "Nilou",
    element: "hydro",
    icon: "images/Nilou.png",
  },
  {
    name: "Ningguang",
    element: "geo",
    icon: "images/Ningguang.png",
  },
  {
    name: "Noelle",
    element: "geo",
    icon: "images/Noelle.png",
  },
  {
    name: "Qiqi",
    element: "cryo",
    icon: "images/Qiqi.png",
  },
  {
    name: "Raiden Shogun",
    element: "electro",
    icon: "images/Raiden Shogun.png",
  },
  {
    name: "Razor",
    element: "electro",
    icon: "images/Razor.png",
  },
  {
    name: "Rosaria",
    element: "cryo",
    icon: "images/Rosaria.png",
  },
  {
    name: "Sangonomiya Kokomi",
    element: "hydro",
    icon: "images/Sangonomiya Kokomi.png",
  },
  {
    name: "Sayu",
    element: "anemo",
    icon: "images/Sayu.png",
  },
  {
    name: "Shenhe",
    element: "cryo",
    icon: "images/Shenhe.png",
  },
  {
    name: "Shikanoin Heizou",
    element: "anemo",
    icon: "images/Shikanoin Heizou.png",
  },
  {
    name: "Sucrose",
    element: "anemo",
    icon: "images/Sucrose.png",
  },
  {
    name: "Tartaglia",
    element: "hydro",
    icon: "images/Tartaglia.png",
  },
  {
    name: "Thoma",
    element: "pyro",
    icon: "images/Thoma.png",
  },
  {
    name: "Tighnari",
    element: "dendro",
    icon: "images/Tighnari.png",
  },
  {
    name: "Traveler (Anemo)",
    element: "anemo",
    icon: "images/Traveler (Anemo).png",
  },
  {
    name: "Traveler (Geo)",
    element: "anemo",
    icon: "images/Traveler (Geo).png",
  },
  {
    name: "Traveler (Electro)",
    element: "anemo",
    icon: "images/Traveler (Electro).png",
  },
  {
    name: "Traveler (Dendro)",
    element: "anemo",
    icon: "images/Traveler (Dendro).png",
  },
  {
    name: "Traveler (Hydro)",
    element: "anemo",
    icon: "images/Traveler (Hydro).png",
  },
  {
    name: "Venti",
    element: "anemo",
    icon: "images/Venti.png",
  },
  {
    name: "Wanderer",
    element: "anemo",
    icon: "images/Wanderer.png",
  },
  {
    name: "Wriothesley",
    element: "cryo",
    icon: "images/Wriothesley.png",
  },
  {
    name: "Xiangling",
    element: "pyro",
    icon: "images/Xiangling.png",
  },
  {
    name: "Xiao",
    element: "anemo",
    icon: "images/Xiao.png",
  },
  {
    name: "Xingqiu",
    element: "hydro",
    icon: "images/Xingqiu.png",
  },
  {
    name: "Xinyan",
    element: "pyro",
    icon: "images/Xinyan.png",
  },
  {
    name: "Yae Miko",
    element: "electro",
    icon: "images/Yae Miko.png",
  },
  {
    name: "Yanfei",
    element: "pyro",
    icon: "images/Yanfei.png",
  },
  {
    name: "Yaoyao",
    element: "anemo",
    icon: "images/Yaoyao.png",
  },
  {
    name: "Yelan",
    element: "hydro",
    icon: "images/Yelan.png",
  },
  {
    name: "Yoimiya",
    element: "pyro",
    icon: "images/Yoimiya.png",
  },
  {
    name: "Yun Jin",
    element: "geo",
    icon: "images/Yun Jin.png",
  },
  {
    name: "Zhongli",
    element: "geo",
    icon: "images/Zhongli.png",
  },
  {
    name: "Xianyun",
    element: "anemo",
    icon: "images/Xianyun.png",
  },
  {
    name: "Gaming",
    element: "pyro",
    icon: "images/Gaming.png",
  },
];

let teams = [
  ["Albedo", "Arataki Itto", "Gorou", "Kuki Shinobu"],
  ["Albedo", "Noelle", "Gorou", "Yun Jin"],
  ["Albedo", "Zhongli", "Hu Tao", "Xingqiu"],
  ["Albedo", "Zhongli", "Xiao", "Faruzan"],
  ["Alhaitham", "Beidou", "Kuki Shinobu", "Nahida"],
  ["Alhaitham", "Yelan", "Kuki Shinobu", "Nahida"],
  ["Alhaitham", "Xingqiu", "Thoma", "Fischl"],
  ["Aloy", "Bennett", "Kaedehara Kazuha", "Xiangling"],
  ["Aloy", "Bennett", "Xiangling", "Shenhe"],
  ["Aloy", "Kamisato Ayaka", "Kaedehara Kazuha", "Sangonomiya Kokomi"],
  ["Aloy", "Ganyu", "Venti", "Mona"],
  ["Amber", "Rosaria", "Layla", "Bennett"],
  ["Amber", "Collei", "Sangonomiya Kokomi", "Rosaria"],
  ["Arataki Itto", "Gorou", "Albedo", "Zhongli"],
  ["Arataki Itto", "Albedo", "Gorou", "Layla"],
  ["Arataki Itto", "Albedo", "Gorou", "Bennett"],
  ["Arataki Itto", "Albedo", "Gorou", "Fischl"],
  ["Baizhu", "Keqing", "Fischl", "Kaedehara Kazuha"],
  ["Baizhu", "Cyno", "Beidou", "Nahida"],
  ["Baizhu", "Nilou", "Sangonomiya Kokomi", "Nahida"],
  ["Barbara", "Xiangling", "Bennett", "Sucrose"],
  ["Barbara", "Jean", "Bennett", "Kaedehara Kazuha"],
  ["Beidou", "Sucrose", "Fischl", "Xingqiu"],
  ["Bennett", "Ganyu", "Xiangling", "Zhongli"],
  ["Bennett", "Chongyun", "Kaedehara Kazuha", "Diona"],
  ["Candace", "Yaoyao", "Nilou", "Traveler (Dendro)"],
  ["Candace", "Beidou", "Kuki Shinobu", "Traveler (Dendro)"],
  ["Candace", "Beidou", "Raiden Shogun", "Nahida"],
  ["Candace", "Collei", "Bennett", "Kaedehara Kazuha"],
  ["Charlotte", "Furina", "Kaedehara Kazuha", "Neuvillette"],
  ["Charlotte", "Furina", "Hu Tao", "Rosaria"],
  ["Charlotte", "Furina", "Kaedehara Kazuha", "Yelan"],
  ["Charlotte", "Kamisato Ayaka", "Venti", "Furina"],
  ["Chevreuse", "Xiangling", "Raiden Shogun", "Bennett"],
  ["Chevreuse", "Fischl", "Yoimiya", "Bennett"],
  ["Chevreuse", "Fischl", "Yae Miko", "Bennett"],
  ["Chevreuse", "Fischl", "Beidou", "Yanfei"],
  ["Chongyun", "Shenhe", "Xianyun", "Xiangling"],
  ["Collei"],
  ["Cyno", "Nahida", "Yelan", "Kuki Shinobu"],
  ["Cyno", "Nahida", "Xingqiu", "Baizhu"],
  ["Cyno", "Nahida", "Fischl", "Baizhu"],
  ["Cyno", "Yaoyao", "Fischl", "Kaedehara Kazuha"],
  ["Cyno", "Nahida", "Yae Miko", "Zhongli"],
  ["Cyno", "Traveler (Dendro)", "Xingqiu", "Beidou"],
  ["Dehya", "Bennett", "Xiangling", "Kaedehara Kazuha"],
  ["Dehya", "Bennett", "Xiangling", "Ganyu"],
  ["Dehya", "Bennett", "Nahida", "Ganyu"],
  ["Dehya", "Bennett", "Lyney", "Kaedehara Kazuha"],
  ["Dehya", "Bennett", "Mona", "Kaedehara Kazuha"],
  ["Dehya", "Bennett", "Faruzan", "Wanderer"],
  ["Dehya", "Xingqiu", "Nahida", "Kuki Shinobu"],
  ["Dehya", "Hu Tao", "Yelan", "Kaedehara Kazuha"],
  ["Dehya", "Yoimiya", "Yelan", "Xingqiu"],
  ["Diluc", "Rosaria", "Bennett", "Sucrose"],
  ["Diluc", "Kaeya", "Bennett", "Sucrose"],
  ["Diluc", "Kaeya", "Bennett", "Kaedehara Kazuha"],
  ["Diluc", "Xingqiu", "Bennett", "Sucrose"],
  ["Diluc", "Xingqiu", "Bennett", "Yelan"],
  ["Diluc", "Xingqiu", "Bennett", "Fischl"],
  ["Diluc", "Xingqiu", "Sucrose", "Fischl"],
  ["Diluc", "Xingqiu", "Beidou", "Fischl"],
  ["Diluc", "Xingqiu", "Albedo", "Zhongli"],
  ["Diluc", "Furina", "Bennett", "Xianyun"],
  ["Diona"],
  ["Dori", "Jean", "Nahida", "Tartaglia"],
  ["Dori", "Jean", "Nahida", "Yelan"],
  ["Dori", "Jean", "Traveler (Dendro)", "Xingqiu"],
  ["Dori", "Eula", "Shenhe", "Rosaria"],
  ["Eula", "Fischl", "Diona", "Rosaria"],
  ["Eula", "Kuki Shinobu", "Shenhe", "Rosaria"],
  ["Eula", "Raiden Shogun", "Diona", "Rosaria"],
  ["Eula", "Raiden Shogun", "Diona", "Lisa"],
  ["Eula", "Raiden Shogun", "Diona", "Yelan"],
  ["Eula", "Raiden Shogun", "Zhongli", "Rosaria"],
  ["Eula", "Fischl", "Beidou", "Diona"],
  ["Faruzan"],
  ["Fischl"],
  ["Freminet", "Xingqiu", "Fischl", "Layla"],
  ["Freminet", "Xingqiu", "Lynette", "Layla"],
  ["Freminet", "Yelan", "Jean", "Shenhe"],
  ["Freminet", "Xingqiu", "Fischl", "Beidou"],
  ["Freminet", "Yelan", "Kuki Shinobu", "Shenhe"],
  ["Freminet", "Sangonomiya Kokomi", "Yae Miko", "Rosaria"],
  ["Freminet", "Sangonomiya Kokomi", "Kaedehara Kazuha", "Rosaria"],
  ["Freminet", "Chongyun", "Kaedehara Kazuha", "Xingqiu"],
  ["Furina", "Zhongli", "Neuvillette", "Kaedehara Kazuha"],
  ["Furina", "Kaedehara Kazuha", "Sangonomiya Kokomi", "Xingqiu"],
  ["Furina", "Mika", "Yelan", "Wriothesley"],
  ["Furina", "Noelle", "Gorou", "Albedo"],
  ["Furina", "Bennett", "Xiangling", "Xingqiu"],
  ["Furina", "Baizhu", "Cyno", "Nahida"],
  ["Furina", "Baizhu", "Raiden Shogun", "Alhaitham"],
  ["Furina", "Yaoyao", "Collei", "Nilou"],
  ["Furina", "Mika", "Eula", "Raiden Shogun"],
  ["Furina", "Mika", "Faruzan", "Wanderer"],
  ["Furina", "Jean", "Hu Tao", "Xingqiu"],
  ["Ganyu", "Venti", "Mona", "Layla"],
  ["Ganyu", "Venti", "Mona", "Rosaria"],
  ["Ganyu", "Venti", "Mona", "Shenhe"],
  ["Ganyu", "Kaedehara Kazuha", "Mona", "Layla"],
  ["Ganyu", "Kaedehara Kazuha", "Mona", "Diona"],
  ["Ganyu", "Venti", "Sangonomiya Kokomi", "Shenhe"],
  ["Ganyu", "Venti", "Sangonomiya Kokomi", "Rosaria"],
  ["Ganyu", "Venti", "Nilou", "Rosaria"],
  ["Ganyu", "Kaedehara Kazuha", "Sangonomiya Kokomi", "Kamisato Ayaka"],
  ["Ganyu", "Bennett", "Xiangling", "Zhongli"],
  ["Ganyu", "Bennett", "Nahida", "Zhongli"],
  ["Ganyu", "Bennett", "Nahida", "Xinyan"],
  ["Ganyu", "Bennett", "Nahida", "Kaedehara Kazuha"],
  ["Gorou"],
  ["Hu Tao"],
  ["Kaedehara Kazuha"],
  ["Kaeya"],
  ["Kamisato Ayaka"],
  ["Kamisato Ayato", "Bennett", "Fischl", "Kaedehara Kazuha"],
  ["Kamisato Ayato", "Yae Miko", "Fischl", "Jean"],
  ["Kamisato Ayato", "Beidou", "Fischl", "Jean"],
  ["Kamisato Ayato", "Beidou", "Fischl", "Bennett"],
  ["Kamisato Ayato", "Bennett", "Xiangling", "Fischl"],
  ["Kamisato Ayato", "Bennett", "Xiangling", "Kaedehara Kazuha"],
  ["Kamisato Ayato", "Bennett", "Xiangling", "Sucrose"],
  ["Kamisato Ayato", "Ganyu", "Diona", "Venti"],
  ["Kamisato Ayato", "Rosaria", "Kaeya", "Kaedehara Kazuha"],
  ["Kaveh", "Nilou", "Baizhu", "Xingqiu"],
  ["Kaveh", "Xingqiu", "Sangonomiya Kokomi", "Kaedehara Kazuha"],
  ["Kaveh", "Nahida", "Sangonomiya Kokomi", "Yelan"],
  ["Kaveh", "Thoma", "Fischl", "Xingqiu"],
  ["Kaveh", "Yelan", "Kaedehara Kazuha", "Bennett"],
  ["Kaveh", "Raiden Shogun", "Traveler (Dendro)", "Xingqiu"],
  ["Kaveh", "Kuki Shinobu", "Yelan", "Xingqiu"],
  ["Keqing"],
  ["Kirara"],
  ["Klee", "Kaedehara Kazuha", "Bennett", "Xiangling"],
  ["Klee", "Kaedehara Kazuha", "Bennett", "Venti"],
  ["Klee", "Bennett", "Xingqiu", "Yelan"],
  ["Klee", "Bennett", "Mona", "Venti"],
  ["Klee", "Xingqiu", "Bennett", "Xiangling"],
  ["Klee", "Xingqiu", "Nahida", "Kirara"],
  ["Klee", "Xingqiu", "Nahida", "Baizhu"],
  ["Klee", "Kaedehara Kazuha", "Bennett", "Rosaria"],
  ["Klee", "Beidou", "Bennett", "Fischl"],
  ["Kujou Sara"],
  ["Kuki Shinobu"],
  ["Layla"],
  ["Lisa"],
  ["Lynette"],
  ["Lyney"],
  ["Mika"],
  ["Mona"],
  ["Nahida"],
  ["Navia", "Zhongli", "Fischl", "Bennett"],
  ["Navia", "Ningguang", "Furina", "Sangonomiya Kokomi"],
  ["Navia", "Zhongli", "Furina", "Bennett"],
  ["Neuvillette"],
  ["Nilou"],
  ["Ningguang", "Zhongli", "Yae Miko", "Fischl"],
  ["Ningguang", "Zhongli", "Albedo", "Fischl"],
  ["Ningguang", "Zhongli", "Bennett", "Fischl"],
  ["Ningguang", "Zhongli", "Bennett", "Gorou"],
  ["Ningguang", "Zhongli", "Albedo", "Kujou Sara"],
  ["Ningguang", "Xiangling", "Albedo", "Bennett"],
  ["Noelle"],
  ["Qiqi"],
  ["Raiden Shogun", "Xiangling", "Xingqiu", "Bennett"],
  ["Raiden Shogun", "Sucrose", "Fischl", "Bennett"],
  ["Raiden Shogun", "Lisa", "Venti", "Sangonomiya Kokomi"],
  ["Raiden Shogun", "Nahida", "Traveler (Dendro)", "Sangonomiya Kokomi"],
  ["Raiden Shogun", "Kujou Sara", "Kaedehara Kazuha", "Bennett"],
  ["Raiden Shogun", "Yae Miko", "Kaedehara Kazuha", "Jean"],
  ["Razor", "Albedo", "Zhongli", "Rosaria"],
  ["Razor", "Albedo", "Zhongli", "Xingqiu"],
  ["Razor", "Fischl", "Zhongli", "Rosaria"],
  ["Razor", "Fischl", "Xingqiu", "Diona"],
  ["Razor", "Bennett", "Xingqiu", "Nahida"],
  ["Razor", "Baizhu", "Furina", "Nahida"],
  ["Razor", "Baizhu", "Xingqiu", "Nahida"],
  ["Razor", "Baizhu", "Yelan", "Nahida"],
  ["Razor", "Xingqiu", "Yelan", "Qiqi"],
  ["Rosaria"],
  ["Sangonomiya Kokomi"],
  ["Sayu", "Keqing", "Traveler (Dendro)", "Fischl"],
  ["Sayu", "Xiao", "Zhongli", "Fischl"],
  ["Sayu", "Bennett", "Xiangling", "Kaedehara Kazuha"],
  ["Sayu", "Sangonomiya Kokomi", "Rosaria", "Bennett"],
  ["Sayu", "Kaeya", "Xiangling", "Bennett"],
  ["Sayu", "Sangonomiya Kokomi", "Fischl", "Sucrose"],
  ["Sayu", "Sangonomiya Kokomi", "Nahida", "Kuki Shinobu"],
  ["Sayu", "Nahida", "Fischl", "Lisa"],
  ["Sayu", "Nahida", "Fischl", "Beidou"],
  ["Shenhe"],
  ["Shikanoin Heizou", "Hu Tao", "Thoma", "Xingqiu"],
  ["Shikanoin Heizou", "Bennett", "Xiangling", "Tartaglia"],
  ["Shikanoin Heizou", "Bennett", "Xiangling", "Xingqiu"],
  ["Shikanoin Heizou", "Bennett", "Xiangling", "Rosaria"],
  ["Shikanoin Heizou", "Bennett", "Xiangling", "Kaedehara Kazuha"],
  ["Shikanoin Heizou", "Bennett", "Xiangling", "Faruzan"],
  ["Sucrose"],
  ["Tartaglia", "Bennett", "Xiangling", "Sucrose"],
  ["Tartaglia", "Bennett", "Xiangling", "Venti"],
  ["Tartaglia", "Bennett", "Xiangling", "Jean"],
  ["Tartaglia", "Bennett", "Xiangling", "Albedo"],
  ["Tartaglia", "Bennett", "Xiangling", "Zhongli"],
  ["Tartaglia", "Bennett", "Xiangling", "Xingqiu"],
  ["Tartaglia", "Bennett", "Xiangling", "Traveler (Anemo)"],
  ["Tartaglia", "Bennett", "Xiangling", "Kaedehara Kazuha"],
  ["Tartaglia", "Bennett", "Beidou", "Kujou Sara"],
  ["Tartaglia", "Bennett", "Beidou", "Fischl"],
  ["Tartaglia", "Bennett", "Beidou", "Yae Miko"],
  ["Tartaglia", "Bennett", "Xiangling", "Fischl"],
  ["Thoma"],
  ["Tighnari", "Fischl", "Kuki Shinobu", "Kaedehara Kazuha"],
  ["Tighnari", "Fischl", "Yae Miko", "Zhongli"],
  ["Tighnari", "Fischl", "Nahida", "Zhongli"],
  ["Tighnari", "Fischl", "Collei", "Bennett"],
  ["Tighnari", "Fischl", "Albedo", "Zhongli"],
  ["Traveler (Dendro)", "Fischl", "Xingqiu", "Sucrose"],
  ["Traveler (Electro)", "Noelle", "Gorou", "Fischl"],
  ["Traveler (Geo)", "Noelle", "Gorou", "Fischl"],
  ["Venti"],
  ["Wanderer"],
  ["Wriothesley", "Nahida", "Bennett", "Thoma"],
  ["Wriothesley", "Xiangling", "Bennett", "Furina"],
  ["Xiangling"],
  ["Xiao", "Faruzan", "Furina", "Xianyun"],
  ["Xingqiu"],
  ["Yae Miko"],
  ["Yanfei"],
  ["Yaoyao"],
  ["Yelan"],
  ["Yoimiya"],
  ["Yun Jin"],
  ["Zhongli"],
  ["Xianyun"],
  ["Gaming", "Xianyun", "Furina", "Bennett"],
];

let links = teams.reduce((acc, val) => {
  for (let i = 0; i < val.length; i++) {
    for (let j = i + 1; j < val.length; j++) {
      acc.push({
        source: val[i],
        target: val[j],
      });
    }
  }
  return acc;
}, []);

var graph = {
  nodes: [...characters],
  links: [...links],
};
